### ISSUE TITLE
Support wss

### ISSUE THREAD

**Issue by willscott** [freedomjs/socialrouter#1]
The server should be upgraded per https://stackoverflow.com/questions/5994549/how-can-i-implement-a-secure-websocket-wss-server-in-python

Currently when code is running on an https based protocol and contacts this server it's a security vulnerability and in new versions of chrome that access will be disallowed.

Should be free to get the certs from startssl.com.

**Comment by agallant** [comment]
Bumping into this now, so taking a look. Will focus on using certs from letsencrypt.org.

**Comment by willscott** [comment]
i think the main thing we've had with social router so far is what the nginx config needs to be for acting as a reverse proxy for web sockets.

right now the python thing is already running behind an nginx forwarder dealing with SNI on my server. it's trivial for me to add letsencrypt/SSL to that NGINX process, but the other thing that needs to be investigated is how to make the connections not drop after ~1min, which i suspect is a timeout in nginx not knowing that they're meant to be long-lived.

**Comment by agallant** [comment]
Alright - last I checked I think the server you were running stopped responding, so I started one at social.dorabella.io but it doesn't do any of the reverse proxy tricks so it's just plain ws. I'll look into adding that, but also want to note that I ran into https://github.com/mail-in-a-box/free_tls_certificates which may be a nice way to eventually make this tool provision its own certificates.

**Comment by willscott** [comment]
https://p2pbr.com/route is up again. do we need the /mailbox socialmailbox thing as well?

**Comment by agallant** [comment]
Not familiar with the /mailbox, so not as far as I know.
